### ISSUE TITLE
Config via Environment Variables

### ISSUE THREAD

**Issue by uschtwill** [gesellix/couchdb-exporter#3]
https://github.com/gesellix/couchdb-exporter/issues/1#issuecomment-249380519

Would be pretty handy... ;)

**Comment by uschtwill** [comment]
Right... I just stumbled over this one again. :)

**Comment by gesellix** [comment]
Note to self: this one seems to be the most promising package to read flags via different input methods: https://github.com/namsral/flag. Maybe https://github.com/alecthomas/kingpin or https://github.com/spf13/viper are possible, too.

**Comment by gesellix** [comment]
@uschtwill please give the latest version a try. Due to backwards compatibility I kept the dot in env variables, which might become a bit uncomfortable when using a shell like bash. You can work around it by running the exporter like this:

    env "COUCHDB.URI=http://localhost:4556" ./couchdb-exporter

**Comment by uschtwill** [comment]
I am only getting:

```
couchdbstats_dev_1           | flag provided but not defined: -telemetry.address
couchdbstats_dev_1           | Usage of /bin/couchdb-exporter:
couchdbstats_dev_1           |   -alsologtostderr
couchdbstats_dev_1           |          log to standard error as well as files
couchdbstats_dev_1           |   -insecure
couchdbstats_dev_1           |          Ignore server certificate if using https (default true)
[...]
```

Not sure, if I am missing something...

**Comment by gesellix** [comment]
Sorry, my bad... that was a little confusion of different flags packages. Should work now!

**Comment by uschtwill** [comment]
Okay, that works. Thanks! :)

Now, my use case is running the exporter from a docker-compose.yml and providing the CouchDB credentials via env vars from an `env_file`. Unfortunately docker doesn't seem to honor env vars with a dot either?! 

What to do? Putting them into the `command:` or `entrypoint:` lines of the docker_compose.yml like your example implies doesn't seem very practical either, given that the idea is to keep the credentials out of version control and that's where that .yml lives. ;)

**Comment by gesellix** [comment]
Alright, I'll use [that one](https://github.com/gesellix/couchdb-exporter/issues/1#issuecomment-249381340) as test case again. Stay tuned :)

**Comment by gesellix** [comment]
🤔 ...

This one works for me: `docker run -it --rm --env-file .couchdb-env -p 9985:9984 --network couchdb-test gesellix/couchdb-exporter -couchdb.uri=http://couchdb:5984/ -logtostderr`.

This one does not:

````
version: "2"

services:
  couchdb:
    image: klaemo/couchdb:2.0-single
    restart: always
    networks:
      - couchdb-test
    expose:
      - 5984
    ports:
      - "5984:5984"
    volumes:
      - couchdb-test:/opt/couchdb/data
    env_file: .couchdb-env

  couchdbstats:
    image: gesellix/couchdb-exporter
    command: -couchdb.uri=http://couchdb:5984/ -couchdb.username=root
#    command: -couchdb.uri=http://couchdb:5984/ -couchdb.username=root -couchdb.password=a-secret
    networks:
      - couchdb-test
    expose:
      - 9984
    ports:
      - "9984:9984"
    env_file: .couchdb-env

networks:
  couchdb-test:
    external: true

volumes:
  couchdb-test:
    external: true
````
